# Generated by Django 5.0.1 on 2024-08-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eturf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfname', models.CharField(max_length=200)),
                ('locationimage', models.ImageField(upload_to='')),
                ('turflocation', models.TextField()),
                ('BookingPackage', models.TextField()),
                ('Facilities', models.TextField()),
                ('Time', models.TextField()),
            ],
        ),
    ]
