# Generated by Django 5.0.1 on 2024-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_eturf_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eturf',
            name='turflocation',
        ),
        migrations.AddField(
            model_name='eturf',
            name='locationname',
            field=models.TextField(default=''),
        ),
    ]
