# Generated by Django 5.0.1 on 2024-09-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_bookingpackage_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
