# Generated by Django 5.0.1 on 2024-09-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_eturf_turflocation_eturf_locationname'),
        ('Users', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='turfid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Admin.eturf'),
            preserve_default=False,
        ),
    ]
