# Generated by Django 5.0.1 on 2024-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_booking_turfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Email',
            field=models.TextField(default=''),
        ),
    ]
