# Generated by Django 5.0.1 on 2024-09-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_turfid_booking_bookingpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingPackage',
            new_name='turfname',
        ),
    ]
