# Generated by Django 5.0.1 on 2024-09-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_remove_register_username_register_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Managername',
            new_name='username',
        ),
    ]
