# Generated by Django 5.0.1 on 2024-09-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_rename_managername_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Managerimage',
        ),
    ]
